# tasks file for haproxy
---
- name: configuration | update file
  template:
    src: "{{ haproxy_conf_template }}"
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0640
    validate: 'haproxy -f %s -c'
#  notify: restart haproxy
  tags:
    - haproxy-configuration-update-file
- name: Remove blank lines in haproxy.conf
  replace:
    path: /etc/haproxy/haproxy.cfg
    regexp: '(^\s*$)'
    replace: ''
    validate: 'haproxy -f %s -c'
  notify: restart haproxy
  tags:
    - haproxy-configuration-update-file
